### ISSUE TITLE
cppreflect segmentation fault

### ISSUE THREAD

**Issue by cscli** [fatedier/fatest#3]
make clean;make 
rm -f *.o
rm -f core*
rm dd
g++ -g -c -o dd.o dd.cpp
g++ -g -c -o reflect.o reflect.cpp
g++ -g -o dd dd.o reflect.o
[root@xx cppreflect]# ./dd
Segmentation fault (core dumped)

**Comment by cscli** [comment]
change the Makefile;   "g++ -o dd dd.o reflect.o" ---> "g++ -o dd reflect.o dd.o"

[root@xx cppreflect]# cat Makefile 
dd:dd.o reflect.o
	g++ -o dd reflect.o dd.o

dd.o:dd.cpp
	g++ -c -o dd.o dd.cpp

reflect.o:reflect.cpp
	g++ -c -o reflect.o reflect.cpp

clean:
	rm -f *.o
	rm -f core*
	rm dd
[root@xx cppreflect]# make clean;make 
rm -f *.o
rm -f core*
rm dd
g++ -c -o dd.o dd.cpp
g++ -c -o reflect.o reflect.cpp
g++ -o dd reflect.o dd.o
[root@xx cppreflect]# ./dd GSBank
拼工商银行报文
发送工商银行报文
接收工商银行报文
解析工商银行报文

**Comment by fatedier** [comment]
Updated. Thanks for your report.
